In [211]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [212]:

df = pd.read_csv(
    '/content/Resume.csv',
    engine='python',          # handles complex text
    on_bad_lines='skip',      # skips corrupted rows
    encoding='utf-8'
)

In [213]:
df.head()

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR

In [214]:
df.shape

(2484, 4)

In [215]:
df.isnull().sum()

ID             0
Resume_str     0
Resume_html    0
Category       0
dtype: int64

In [216]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2484 entries, 0 to 2483
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           2484 non-null   int64
 1   Resume_str   2484 non-null   object
 2   Resume_html  2484 non-null   object
 3   Category     2484 non-null   object
dtypes: int64(1), object(3)
memory usage: 77.8+ KB

In [217]:
df['Category'].value_counts()

Category
INFORMATION-TECHNOLOGY    120
BUSINESS-DEVELOPMENT      120
ADVOCATE                  118
CHEF                      118
ENGINEERING               118
ACCOUNTANT                118
FINANCE                   118
FITNESS                   117
AVIATION                  117
SALES                     116
BANKING                   115
HEALTHCARE                115
CONSULTANT                115
CONSTRUCTION              112
PUBLIC-RELATIONS          111
HR                        110
DESIGNER                  107
ARTS                      103
TEACHER                   102
APPAREL                    97
DIGITAL-MEDIA              96
AGRICULTURE                63
AUTOMOBILE                 36
BPO                        22
Name: count, dtype: int64

In [218]:
df[['Resume_str', 'Resume_html', 'Category']].sample(2)

,Resume_str,Resume_html,Category
2125,GENERAL MANAGER Professional ...,"<div class=""fontsize fontface vmargins hmargin...",PUBLIC-RELATIONS
2133,TRANSFER RECRUITER/ADMISSIONS COUNSEL...,"<div class=""fontsize fontface vmargins hmargin...",PUBLIC-RELATIONS

In [219]:
#converting all text into lowercase
df.columns = df.columns.str.lower()
df['resume_str']=df['resume_str'].str.lower()
df['category']=df['category'].str.lower()
df['resume_html']=df['resume_str'].str.lower()

In [220]:
df.head()

,id,resume_str,resume_html,category
0,16852973,hr administrator/marketing associate\...,hr administrator/marketing associate\...,hr
1,22323967,"hr specialist, us hr operations ...","hr specialist, us hr operations ...",hr
2,33176873,hr director summary over 2...,hr director summary over 2...,hr
3,27018550,hr specialist summary dedica...,hr specialist summary dedica...,hr
4,17812897,hr manager skill highlights ...,hr manager skill highlights ...,hr

In [221]:
def clean_resume(text):
    text = re.sub(r'http\S+|www\S+', '', text)      # remove URLs
    text = re.sub(r'\S+@\S+', '', text)            # remove emails
    text = re.sub(r'\d+', '', text)                # remove numbers
    text = re.sub(r'[^a-zA-Z\s]', '', text)        # remove special characters
    text = text.lower()                            # lowercase
    text = text.strip()                            # remove extra spaces
    return text

df['resume_str'] = df['resume_str'].apply(clean_resume)

df['resume_html'] = df['resume_html'].apply(clean_resume)

In [222]:
from bs4 import BeautifulSoup

def remove_html_tags(text):
    soup = BeautifulSoup(text, "html.parser")
    return soup.get_text()

df['resume_html'] = df['resume_html'].apply(remove_html_tags)

In [223]:
df.head()

,id,resume_str,resume_html,category
0,16852973,hr administratormarketing associate\n\nhr admi...,hr administratormarketing associate\n\nhr admi...,hr
1,22323967,hr specialist us hr operations summary ...,hr specialist us hr operations summary ...,hr
2,33176873,hr director summary over years exp...,hr director summary over years exp...,hr
3,27018550,hr specialist summary dedicated drive...,hr specialist summary dedicated drive...,hr
4,17812897,hr manager skill highlights ...,hr manager skill highlights ...,hr

In [224]:
df[['resume_str','resume_html']].sample(5)

,resume_str,resume_html
1670,key holder sales planner summary art ...,key holder sales planner summary art ...
1696,engineering technician professional summ...,engineering technician professional summ...
54,hr specialist summary resultsdriven p...,hr specialist summary resultsdriven p...
2090,about creative communications professional ...,about creative communications professional ...
269,information technology specialist ex...,information technology specialist ex...

In [225]:
#both are exactly same
(df['resume_str'] == df['resume_html']).sum()

np.int64(2484)

In [226]:
df = df.drop(columns=['resume_html','id'])

In [227]:
df.head()

                                          resume_str category
0  hr administratormarketing associate\n\nhr admi...       hr
1  hr specialist us hr operations       summary  ...       hr
2  hr director       summary      over  years exp...       hr
3  hr specialist       summary    dedicated drive...       hr
4  hr manager         skill highlights           ...       hr

In [228]:
df['resume_str'][0]

'hr administratormarketing associate\n\nhr administrator       summary     dedicated customer service manager with  years of experience in hospitality and customer service management   respected builder and leader of customerfocused teams strives to instill a shared enthusiastic commitment to customer service         highlights         focused on customer satisfaction  team management  marketing savvy  conflict resolution techniques     training and development  skilled multitasker  client relations specialist           accomplishments      missouri dot supervisor training certification  certified by ihg in customer loyalty and marketing by segment   hilton worldwide general manager training certification  accomplished trainer for cross server hospitality systems such as    hilton onq     micros    opera pms    fidelio    opera    reservation system ors    holidex    completed courses and seminars in customer service sales strategies inventory control loss prevention safety time management leadership and performance assessment        experience      hr administratormarketing associate\n\nhr administrator     dec    to   current      company name      city     state     helps to develop policies directs and coordinates activities such as employment compensation labor relations benefits training and employee services  prepares employee separation notices and related documentation  keeps records of benefits plans participation such as insurance and pension plan personnel transactions such as hires promotions transfers performance reviews and terminations and employee statistics for government reporting  advises management in appropriate resolution of employee relations issues  administers benefits programs such as life health dental insurance pension plans vacation sick leave leave of absence and employee assistance     marketing associate \xa0   designed and created marketing collateral for sales meetings trade shows and company executives  managed the inhouse advertising program consisting of print and media collateral pieces  assisted in the complete design and launch of the companys website in  months  created an official company page on facebook to facilitate interaction with customers  analyzed ratings and programming features of competitors to evaluate the effectiveness of marketing strategies         advanced medical claims analyst     mar    to   dec       company name      city     state     reviewed medical bills for the accuracy of the treatments tests and hospital stays prior to sanctioning the claims  trained to interpret the codes icd cpt and terminology commonly used in medical billing to fully understand the paperwork that is submitted by healthcare providers  required to have organizational and analytical skills as well as computer skills knowledge of medical terminology and procedures statistics billing standards data analysis and laws regarding medical billing         assistant general manager     jun    to   dec       company name      city     state     performed duties including but not limited to budgeting and financial management accounting human resources payroll and purchasing  established and maintained close working relationships with all departments of the hotel to ensure maximum operation productivity morale and guest service  handled daily operations and reported directly to the corporate office  hired and trained staff on overall objectives and goals with an emphasis on high customer service  marketing and advertising working on public relations with the media government and local businesses and chamber of commerce         executive support  marketing assistant     jul    to   jun       company name      city     state     provided assistance to various department heads  executive marketing customer service human resources  managed frontend operations to ensure friendly and efficient transactions  ensured the swift resolution of customer issues to preserve customer loyalty while complying with company policies  exemplified the secondtonone customer service delivery in all interactions with customers and potential clients         reservation  front office manager     jun    to   jul       company name      city     state          owner partner     dec    to   may       company name      city     state          price integrity coordinator     aug    to   dec       company name      city     state          education      na     business administration        jefferson college      city     state       business administration  marketing  advertising         high school diploma     college prep studies        sainte genevieve senior high      city     state       awarded american shrubel leadership scholarship to jefferson college         skills     accounting ads advertising analytical skills benefits billing budgeting clients customer service data analysis delivery documentation employee relations financial management government relations human resources insurance labor relations layout marketing marketing collateral medical billing medical terminology office organizational payroll performance reviews personnel policies posters presentations public relations purchasing reporting statistics website'

In [229]:
import re

def clean_text_advanced(text):
    text = str(text)

    # 1. Replace newline characters with space
    text = re.sub(r'\n+', ' ', text)

    # 2. Add space between joined words (lowercase + uppercase OR word boundaries)
    text = re.sub(r'([a-z])([A-Z])', r'\1 \2', text)

    # 3. Fix merged common words (custom fixes if needed)
    text = re.sub(r'administratormarketing', 'administrator marketing', text)

    # 4. Remove special characters like ,,,
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)

    # 5. Remove extra spaces
    text = re.sub(r'\s+', ' ', text)

    # 6. Lowercase
    text = text.lower().strip()


    return text

df['resume_str'] = df['resume_str'].apply(clean_text_advanced)

In [230]:
from nltk.stem import PorterStemmer
stemmer=PorterStemmer()
df['tokens'] = df['resume_str'].apply(lambda x: x.split())
df['tokens'] = df['tokens'].apply(
    lambda words: [stemmer.stem(word) for word in words]
)
df['resume_str'] = df['tokens'].apply(lambda x: " ".join(x))

In [231]:
df.head()

,resume_str,category,tokens
0,hr administr market associ hr administr summar...,hr,"[hr, administr, market, associ, hr, administr,..."
1,hr specialist us hr oper summari versatil medi...,hr,"[hr, specialist, us, hr, oper, summari, versat..."
2,hr director summari over year experi in recrui...,hr,"[hr, director, summari, over, year, experi, in..."
3,hr specialist summari dedic driven and dynam w...,hr,"[hr, specialist, summari, dedic, driven, and, ..."
4,hr manag skill highlight hr skill hr depart st...,hr,"[hr, manag, skill, highlight, hr, skill, hr, d..."

In [232]:
df['category'].value_counts()

category
information-technology    120
business-development      120
advocate                  118
chef                      118
engineering               118
accountant                118
finance                   118
fitness                   117
aviation                  117
sales                     116
banking                   115
healthcare                115
consultant                115
construction              112
public-relations          111
hr                        110
designer                  107
arts                      103
teacher                   102
apparel                    97
digital-media              96
agriculture                63
automobile                 36
bpo                        22
Name: count, dtype: int64

words into categorical **values**

In [233]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['category']=le.fit_transform(df['category'])

In [234]:
df.head()

,resume_str,category,tokens
0,hr administr market associ hr administr summar...,19,"[hr, administr, market, associ, hr, administr,..."
1,hr specialist us hr oper summari versatil medi...,19,"[hr, specialist, us, hr, oper, summari, versat..."
2,hr director summari over year experi in recrui...,19,"[hr, director, summari, over, year, experi, in..."
3,hr specialist summari dedic driven and dynam w...,19,"[hr, specialist, summari, dedic, driven, and, ..."
4,hr manag skill highlight hr skill hr depart st...,19,"[hr, manag, skill, highlight, hr, skill, hr, d..."

In [235]:
df.category.unique()

array([19, 13, 20, 23,  1,  9, 18, 17,  2,  8, 22, 12, 14,  5, 10, 16,  3,
       15,  0, 11, 21,  7,  4,  6])

In [236]:
#vecotrization


from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000)
X = tfidf.fit_transform(df['resume_str'])

In [237]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, df['category'], test_size=0.2, random_state=42
)

In [238]:
X_train.shape

(1987, 5000)

In [239]:

X_test.shape

(497, 5000)

Now let’s train the model and print the classification report:

In [246]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Train KNN (NO OneVsRest needed)
knn_model = KNeighborsClassifier(n_neighbors=5, metric='cosine')

knn_model.fit(X_train, y_train)

# Predict
y_pred_knn = knn_model.predict(X_test)

# Evaluation
print("\nKNN Results:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_knn):.4f}")
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_knn))
print("Classification Report:\n", classification_report(y_test, y_pred_knn))

KNN Results:
Accuracy: 0.4849
Confusion Matrix:
 [[25  0  0  0  1  0  0  0  0  0  0  0  1  0  0  0  2  0  0  0  0  0  0  0]
 [ 2 12  1  1  0  0  0  0  0  0  0  0  3  0  1  0  0  1  7  0  0  0  0  2]
 [ 2  0  2  0  0  0  0  0  0  0  0  0  1  0  0  1  0  0  0  0  0  0  0  2]
 [ 0  5  0  6  0  2  0  0  0  1  0  1  0  1  0  1  0  0  1  0  0  0  0  2]
 [ 0  3  0  1  0  0  0  0  0  0  0  0  4  2  0  0  0  0  0  1  0  0  1  6]
 [ 0  2  0  0  1  1  1  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  2  0  0 13  0  0  0  0  0  0  1  0  1  0  0  0  1  3  0  0  0]
 [ 1  0  0  0  0  0  0 11  1  1  0  0  3  0  0  1  3  0  0  0  1  0  1  0]
 [ 0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  2  1  3  0  0  0  2  1 14  0  0  1  0  0  0  0  0  3  0  0  0  0  0]
 [ 0  2  0  1  0  0  3  0  0  0 15  0  1  0  0  0  0  0  1  0  0  0  1  0]
 [ 0  2  1  4  2  0  0  0  0  0  0 22  1  0  0  2  0  0  0  0  0  0  0  0]
 [ 0  1  1  1  0  0  1  0  1  0  0  1  4  1  2  0  0  0  2  1  3  1  0  0]
 [ 0  1  0  3  1  0  0  0  0  0  0  0  1 12  1  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  1  1  0  0  1  0  0  0  0  1  1 14  0  0  0  0  0  1  4  0  0]
 [ 0  0  0  1  0  0  2  0  0  0  0  1  1  2  0 14  0  0  0  0  0  0  0  0]
 [11  0  1  0  0  0  0  0  0  0  0  0  1  0  0  0  4  0  0  1  0  0  1  0]
 [ 1  3  0  1  2  0  4  0  0  1  0  0  0  0  0  0  0  5  2  0  0  0  0  0]
 [ 1  3  0  0  0  0  0  0  0  0  0  0  3  0  1  1  0  0 10  1  0  0  0  0]
 [ 1  0  1  0  0  1  0  0  0  0  0  0  2  0  0  0  0  0  0 13  0  0  0  0]
 [ 0  0  0  1  0  0  0  0  0  0  0  0  8  0  0  2  0  0  0  0 14  0  0  1]
 [ 1  0  0  0  0  0  0  0  0  1  0  0  2  0  0  0  0  0  0  1  1 10  1  0]
 [ 3  9  1  3  0  0  0  1  0  1  0  0  2  0  0  0  0  1  2  0  0  0  6  0]
 [ 0  0  0  0  3  0  0  0  0  0  0  2  1  1  0  0  0  0  0  0  0  1  0 14]]
Classification Report:
               precision    recall  f1-score   support

           0       0.52      0.86      0.65        29
           1       0.26      0.40      0.31        30
           2       0.22      0.25      0.24         8
           3       0.21      0.30      0.24        20
           4       0.00      0.00      0.00        18
           5       0.25      0.17      0.20         6
           6       0.54      0.62      0.58        21
           7       0.73      0.48      0.58        23
           8       0.00      0.00      0.00         2
           9       0.74      0.52      0.61        27
          10       1.00      0.62      0.77        24
          11       0.81      0.65      0.72        34
          12       0.10      0.20      0.13        20
          13       0.57      0.63      0.60        19
          14       0.74      0.56      0.64        25
          15       0.61      0.67      0.64        21
          16       0.40      0.21      0.28        19
          17       0.71      0.26      0.38        19
          18       0.36      0.50      0.42        20
          19       0.68      0.72      0.70        18
          20       0.58      0.54      0.56        26
          21       0.62      0.59      0.61        17
          22       0.55      0.21      0.30        29
          23       0.52      0.64      0.57        22

    accuracy                           0.48       497
   macro avg       0.49      0.44      0.45       497
weighted avg       0.54      0.48      0.49       497

In [247]:
svm_model = SVC(kernel='linear')

svm_model.fit(X_train, y_train)
y_pred_svm = svm_model.predict(X_test)

print("\nSVM Results:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_svm):.4f}")

SVM Results:
Accuracy: 0.6036

In [248]:
lr_model = LogisticRegression(max_iter=1000)

lr_model.fit(X_train, y_train)
y_pred_lr = lr_model.predict(X_test)

print("\nLogistic Regression Results:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_lr):.4f}")

Logistic Regression Results:
Accuracy: 0.6177

In [250]:
rf_model = RandomForestClassifier(n_estimators=100)

rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

print("\nRandom Forest Results:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_rf):.4f}")

Random Forest Results:
Accuracy: 0.6539

In [255]:
results = {
    "KNN": accuracy_score(y_test, y_pred_knn),
    "SVM": accuracy_score(y_test, y_pred_svm),
    "Logistic Regression": accuracy_score(y_test, y_pred_lr),
    "Random Forest": accuracy_score(y_test, y_pred_rf)

}

for model, acc in results.items():
    print(f"{model}: {acc:.4f}")

KNN: 0.4849
SVM: 0.6036
Logistic Regression: 0.6177
Random Forest: 0.6539


Prediction System

In [256]:
def predict_resume_category(input_resume, model, tfidf, label_encoder):
    """
    Predict the category of a resume
    """

    try:
        # 1. Safety check
        if not input_resume or not isinstance(input_resume, str):
            return "Invalid input"

        # 2. Clean text
        cleaned_text = clean_resume(input_resume)

        # 3. Vectorize
        vectorized_text = tfidf.transform([cleaned_text])

        # 4. Predict
        prediction = model.predict(vectorized_text)

        # 5. Decode label
        category = label_encoder.inverse_transform(prediction)

        return category[0]

    except Exception as e:
        return f"Error: {str(e)}"

In [257]:
predict_resume_category("HR manager with 5 years experience", knn_model, tfidf, le)

'hr'

In [267]:
predict_resume_category(
    "england at it doing nothing for 5 years experience",
    rf_model,
    tfidf,
    le
)

'business-development'